### PR TITLE
Bundle size

### LINKED ISSUE #73: Highway bundle size
Hi Dogstudio team! Big fan of Highway 🙂

Noticed recently that the bundle size of Highway has mysteriously grown to a whopping 19kb gzipped while the website still advertises Highway as being 2.5kb gzipped. So, I decided to dig in and try to get to the bottom of this.

Seems like the culprit is [these lines](https://github.com/Dogstudio/highway/blob/0f0172731ab37b2f2f528c6b77bd71e19193f706/webpack.config.js#L37-L46) in the webpack config file which add massive overhead in core-js polyfills. Personally, I don't think it makes sense to ship polyfills in a library, period. Transpiling newer syntax to avoid errors in older browsers is crucial, but decisions around how and when to use and load polyfills should be left to the end-user of the library. Not only does this allow us to ship the smallest possible iteration of Highway to users that may or may not even need to support older browsers, but also because it is common practice to exclude `node_modules` from babel, so that means it would actually be very likely to accidentally include all that core-js overhead _twice_.

After removing those `@babel/preset-env` options mentioned above and implementing the [async-to-promises babel transform](https://github.com/rpetrich/babel-plugin-transform-async-to-promises), the gzipped build is down to 3.5kb 🎉and it's working smoothly in a few of my existing Highway projects.

After sifting through the Highway source code, I believe the only polyfills that would be potentially necessary for users to maintain existing browser support would be:

- [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
- [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
- [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

These polyfills can either be installed manually, or loaded dynamically in browsers that need them via polyfill.io. Simply include this script tag before highway:

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=fetch%2CPromise%2CMap"></script>
```

This would be a breaking change for any Highway users that are not already including polyfills for those features in older browsers, but IMHO shaving off nearly 16.5kb from the gzipped bundle is well worth it.

Looking forward to your feedback. Happy to make a PR.

### PR DESCRIPTION
**Pull request by mikehwagz**
Resolves #73, see the issue for additional context.

Replaces webpack with [microbundle](https://github.com/developit/microbundle) reducing the gzipped size of the library from 19.3kb to an average size of 2.34kb (over 87% smaller):

```
2.46 kB: highway.js.gz
2.19 kB: highway.js.br
2.46 kB: highway.module.js.gz
2.19 kB: highway.module.js.br
2.52 kB: highway.umd.js.gz
2.23 kB: highway.umd.js.br
```

In doing so, there are several considerations:

### ESLint
To replace the webpack eslint configuration, I've added a `lint` npm script. Happy to update this. Maybe it would be worth setting it up as a precommit hook via husky since it will no longer be run automatically on build

### Polyfills
Users of highway that need to maintain support for IE will need to include polyfills for [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), plus a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) polyfill for < IE11 support. As demonstrated in #73, these polyfills can be loaded conditionally via polyfill.io by adding this script tag before highway: 
```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=fetch%2CPromise%2CMap"></script>
```
Because Promise and Map polyfills were not required previously, this would be a breaking change and we would need to update the documentation.

### Output formats
Microbundle outputs common js, module, and umd bundles out of the box. The `unpkg` field in the package.json file automatically resolves the umd build when loaded via [unpkg](https://unpkg.com/). While all microbundle outputs are automatically minified via [terser](https://github.com/terser/terser), perhaps it would be worth renaming the umd build to `highway.min.js` to ease this transition for users that are importing the minified file directly. Let me know what you think about this.

Looking forward to your feedback! 🍻

### CODE REVIEW

**Comment by Anthodpnt** [comment]
Hey @mikehwagz 

That's a great work! Thanks again for the time you spent on this pull request. Everything seems good to us. May we ask you to update the documentation accordingly? You may have to change the list of supported browsers on the homepage. We believe it might make sense to keep IE11 in this list but replace the `whatwg-fetch` mention with a `see example` one that would redirect to a new example about browser support. That example would explain how to use the polyfills to support at least IE11.

For the UMD bundle name, we do agree that renaming it would make the transition easier for users. That being said, once the documentation will be updated, we'll create a new release and describe the breaking changes properly for users as well.

Best regards,
Anthodpnt

**Comment by mikehwagz** [comment]
Thanks for the feedback @Anthodpnt. I've updated the umd bundle filename and added a new Polyfills example which is also linked in the github readme.

Just to be super thorough, I've consolidated relevant browser compatibility for each feature. Let me know if you think it might be helpful to add this table into the readme/docs somewhere!

| Feature | Internet Explorer | Safari |
| --- | --- | --- |
| [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) | ❌ | 10.1+ |
| [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) | ❌ | 8+ |
|[Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) | 11+ | 8+ |

**Comment by Anthodpnt** [comment]
Hey @mikehwagz 

Indeed, I believe this might be a good idea to put this in the README. However, can you tell how this could be useful for users? It's interesting to have this table and know which feature is compatible with which browser but in the end, what's the real purpose of this table? How would it be helpful for users?

Best regards,
Anthodpnt

**Comment by Anthodpnt** [comment]
Also, I'm going to review your PR and come back to you with a feedback as soon as I'm done. Thanks again for your motivation and your help to improve our library!

**Pull request merged**
