### PR TITLE
Contextual transitions

### PR DESCRIPTION
**Pull request by joshkirk-zero**
As proposed, here is the ability to use contextual transitions. Meaning, a transition that fires when clicking a certain link.

Here are some notes:

- Rather than setting the transition in the getTransition function in helpers, we must override the transition on the fly by passing in either the contextual transition or false to transition.js. 
- This is because we don't want to mess with the transition assigned to a view, and we don't want the contextual transition to fire on popstate. It must only fire when clicking a particular link, all other view transitions must be left alone. 
- I tried it several ways, and this was the most reliable way I could accomplish the feature. Perhaps you could think of ways to trim my code more.

------

To accomplish this we:

- Save all transitions to `this.Transitions` in the core constructor
- Also in the core constructor, set `this.contextualTransition` to false (default)
- In `navigate(e)`, check if the clicked anchor has `data-transition` if it does, set `this.contextualTransition` to the transition. Else set it to false.
- In the `hide()` and `show()` functions, we pass in `this.contextualTransition`, which is passed all the way to the transition itself.
- In `transition.js` we check whether the contextual transition is false, if not we use the contextual transition. If it is false, we simply use the transition from the view.
- On popstate, set `this.contextualTransition` to false no matter what, since we should use the default/view transition when navigating via browser buttons.

### CODE REVIEW

**Comment by ThaoD5** [comment]
Woaw @joshkirk-zero great work here, we're definitely going to have a look tomorrow at your solution for this issue ! 

Thanks already for coming up with a complete solution and this nice explaining comment, we will keep you updated as soon as possible, but it seems really promising !

Have a great night!

**Comment by Anthodpnt** [comment]
Thanks @joshkirk-zero! I quickly check the changes committed and it already looks awesome. Give me a bit of time to completely review everything and I'll create a new release when done and keep you in touch here or by email.

**Comment by joshkirk-zero** [comment]
Nice I'm glad you like it 👍 

A couple other small notes now that I've had another night to think about it..

- Feel free to change the name of things to better suit your conventions if you want
- I tried making it as concise as possible, but it felt a little weird having a bool check on every transition. I couldn't think of a less verbose way to do it though. In the end it's just a single false check that's going to hit first, and all of the transitions are just standing by, waiting to fire anyway. At least that was my conclusion, but I've only spent a couple days in the library.
- I hastily added two example transitions and the snippet in the documentation, so feel free to clean those up or add to them however you want.

I can't think of anything else at the moment, but I'm available for further discussion. 

Thank you

**Comment by joshkirk-zero** [comment]
Oh yeah, also I was new to Jekyll, and the way the docs build worked inside the highway build confused me for little bit, so I hope I committed all the relevant files. I think you'll have to run the docs build and the highway build.

**Pull request merged**
